name: Snake

on:
  push:
    branches:
      - main

jobs:
  create-snake-animation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate snake animation
      uses: Platane/snk@master
      with:
        github_user: "JoaovBenjamin"  
        svg_out_path: "github-contribution-grid-snake.svg"

    - name: Commit and push snake animation
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "João Vitor Vicente Benjamin"
        author_email: "joaovvbenjamin@hotmail.com"
        message: "Generate snake animation"
        add: "github-contribution-grid-snake.svg"
